services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 24.0.2
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    volumes:
      - .:/usr/src/app
      - server_node_npm_cache:/root/.npm
    command: node index.js

volumes:
  server_node_npm_cache:
